spring:
  application:
    name: RESTFul Starter based on Spring Boot Framework

  jpa:
    # 控制台打印SQL语句
    show-sql: true
    # 自动搜索Entity对象并创建对应的数据库表，然后使用import.sql文件导入数据
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: true

  # 数据库连接设置
  datasource:
    url: jdbc:h2:mem:dev_db;DATABASE_TO_UPPER=false;
    driver-class-name: org.h2.Driver
    username: root
    password: 123456


    # 开启H2 Web Console并配置访问路径
  h2:
    console:
      path: /h2
      enabled: true

# 日志配置
logging:
  level:
    root: INFO
    org.springframework:
      data: DEBUG
      security: DEBUG
      hibernate: ERROR
    tech.zhaixinyu.starter: DEBUG